### ISSUE TITLE
Healthcheck inconsisten

### ISSUE THREAD

**Issue by nubela** [passbolt/passbolt_docker#126]
Running 

    # su -s /bin/bash -c "./bin/cake passbolt healthcheck" www-data

and visiting https://passbolt.local/healthcheck shows inconsistent results.

The web version of the healthcheck shows that everything is fine, including this line: `The server key fingerprint matches the one defined in config/passbolt.php.`

The weird thing is that in the passbolt container, /var/www/passbolt/config/passbolt.php does not exist. So when I run the cli version of the healthcheck as `su -s /bin/bash -c "./bin/cake passbolt healthcheck" www-data`, I get the following error: 

> [FAIL] The server key fingerprint doesn't match the one defined in config/passbolt.php

What do I do?

---

I am running Passbolt 2.8.1 with a Docker image built from this repo.

**Comment by dlen** [comment]
Hi @nubela 

Thanks for your interest on the project and sorry for the late reply!

Your question triggers a topic that is interesting. If you are relying on the gpg serverkey automagically created by the container on startup the behaviour you experience is expected.

When the container starts checks for a gpg serverkey, if it doesn't exist it creates a new one and identifies its fingerprint which is exported as an env variable for the passbolt process to use [here](https://github.com/passbolt/passbolt_docker/blob/master/bin/docker-entrypoint.sh#L81) 

This means that only the child processes of the docker-entrypoint.sh process will have this environment variable set. So, when you exec on the container you won't have by default the env variable that contains the fingerprint, that's why you see this inconsistency.

This very same behaviour happens with the cron jobs that passbolt runs to send emails. In order to fix this the entrypoint dumps all the passbolt env variables into /etc/environment which is [sourced when running the cronjob](https://github.com/passbolt/passbolt_docker/blob/master/bin/docker-entrypoint.sh#L91)

In your case you could execute the following:

```
su -s /bin/bash -c "source /etc/environment; ./bin/cake passbolt healthcheck" www-data
```

This process is hacky but it was one of the trade offs we made to make the docker container more user friendly (works out of the box). There are plans to change this but currently our resources are very limited to tackle it.

Hope this clear your doubts. I will keep this issue open for future rework of this part.

**Comment by nubela** [comment]
Thanks, yes I figured that the CLI wasn't reading the env vars. With that said, maybe this can be documented?

**Comment by nubela** [comment]
My point being that taking shortcuts is OK, but being documented is less ok.

**Comment by dlen** [comment]
sure thing we will add it on our help site!

**Comment by almereyda** [comment]
Another way of adopting the environment is by using `su -m`, as seen in https://github.com/mmz-srf/passbolt-helm/:

    su -m -c "bin/cake passbolt healthcheck" -s /bin/sh www-data

**Comment by dlen** [comment]
Hi @almereyda this is not entirely true in all scenarios.

Using `-p` or `-m` only works whenever the gpg key and its fingerprint are exported as an env variable when the container is launched. In this situation, any bash shell instance will be able to read the gpg fingerprint env variable.

In the scenario of a user just running passbolt without any gpg key set, the entrypoint will generate a random one on startup for you and export its fingerprint as an env variable to any process that is children of the entrypoint. 
When you connect to a container using `docker exec -ti passbolt-container bash` your bash shell is not a children of the entrypoint so you won't see the gpg fingerprint env variable even using `-m` or `-p` switches in the su command.

I'm closing this issue as it is already documented until we find a better solution. Thanks for the feedback to all of you.
