### ISSUE TITLE
pgp key download

### ISSUE THREAD

**Issue by MarekPep** [passbolt/passbolt_docker#28]
STEPS:
1) Go to: my profile -> menage your keys
2)  try download: private/public key
3) BUG: **No information** about downloading files
INFO: files save correctly

**Comment by stripthis** [comment]
@MarekPep I'm not sure what you consider a bug here since the files are downloading corrrectly. The download behavior (e.g. for example being able to select the location of the file or the windows you see) are outside passbolt remit since they are provided by the browser and it is not something we can control in an extension environment.

Can you elaborate a bit more with what you would expect instead by creating a new issue here: https://github.com/passbolt/passbolt_api/issues ?
