### ISSUE TITLE
After installation default page is Example Domain

### ISSUE THREAD

**Issue by Kantankerus** [passbolt/passbolt_docker#36]
I have installed a MySQL docker container (official), set the appropriate environment variables (MYSQL_ROOT_PASSWORD, MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD) from the documentation and fired it up.  

Next I grabbed the passbolt docker container (official), set env variable of db_host to the IP address of the MySQL container and fired it up...it declares "Passbolt installation succssess!  Enjoy!" but when I go to https://localhost:<port of 443 on container> all I get is an Example Domain placeholder:
![example_domain](https://user-images.githubusercontent.com/7518746/28500589-1f9be4de-6f88-11e7-8303-09484b979ab4.png)

Going to https://[IP of the container], I get a connection error.

Either I'm tripping over something simple or something more serious is afoot.

Any help, hints, gentle nudges or brutal shoves in the right direction would be appreciated.

**Comment by dlen** [comment]
Hi @Kantankerus thanks for your interest in passbolt! This behaviour is due to the default passbolt uses as BaseUrl which is `example.com`. Whenever the application is accessed (doesn't matter if you use the ip address of the container) passbolt automatically redirects subsequent request to the baseurl. So basically it is redirecting you to `example.com` domain.
To fix this behaviour we encourage to use the `url` environment variable when running passbolt container. For instance:
`docker run -e db_host=your_mysql_container_host -e url=passbolt.dev passbolt/passbolt:latest`
Then add to your /etc/hosts
`your_passbolt_container_ip passbolt.dev`
should be working fine.
For test purposes there is a docker-composer repo you might find useful: https://github.com/dlen/passbolt-compose

**Comment by Kantankerus** [comment]
Diego,

I knew it was something simple, thanks!  I'd suggest mentioning the default
in your documention, something like:

   - url: url of the passbolt installation (defaults to example.com)

This would make it a bit more obvious for simpleton's like me and
potentially help with Google searches.

THANK YOU!

-Brock

**Comment by dlen** [comment]
Yes, you are right. It should be mentioned on the README and it will be added ASAP to the README.
Thanks for your suggestions and your interest in passbolt!!
