### ISSUE TITLE
Cannot expose (persist) config directory with docker mount.

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_docker#45]
When trying to mount the whole config directory of the docker externally (for debugging and easier backup) the docker complains of files not being found instead of creating them itself.

-v "/mnt/user/data/docker/":"/var/www/":rw

It seems that the config file create logic is missing in that if there is a user config use it, if not create a new one?

/var/www/passbolt/app/Config/gpg/serverkey.private.asc: No such file or directory

**Comment by dlen** [comment]
Hi @mannp 
Currently the main aim of mounting configuration files is for the users to have a flexible way to provide their complex configuration files and gpg keys to passbolt so they don't rely on env variables. It is not supported right now for an user to mount an empty Config directory and expect passbolt container to populate it. If you want to do such a thing you have to provide the container the directories and initial file structure needed for docker-entrypoint to run from host.
For instance, in order to do what you want to do you should expose from host a directory that contains:
- Directories:
```gpg```
- Files:
```app.php.default, core.php.default, database.php.default, email.php.default```

And this will be just for the `docker-entrypoint.sh` to run, it doesn't give you any warranty that passbolt will run ok with just the above files. To make sure that passbolt works ok you should expose a directory as Config with the structure and files that [passbolt_api provides by default](https://github.com/passbolt/passbolt_api/tree/master/app/Config). Conclusion is passbolt_docker encourages mounting **only** the configuration files with special needs and not the whole Config directory.
The scenario you describe will be considered for future releases though.

One last comment is that if you don't want to go through all this setup/workarounds you can check this [passbolt-compose](https://github.com/dlen/passbolt-compose) that you might find easy to setup

**Comment by mannp** [comment]
@dlen I see, which is great for people who managed to get things setup and working from the start, but anything from the non standard means the config fails and needs manual input.

Having all my dockers config in one place allows easy daily backups and adjustment as I need.

I will go back to trying to edit the database.php again just to test passbolt out.

**Comment by dlen** [comment]
You can still do what you are suggesting, you just have to keep in mind the limitations of your proposed scenario with passbolt docker image. Basically just copy the whole Config default directory from passbolt_api and mount it, you will be good to go.
It is not an elegant solution but a temporary workaround.

**Comment by mannp** [comment]
Thanks @dlen , I must be being dumb as I have other php apps with similar configs working great.

I have done the copy and mounted the Config directory external to the docker and it gets past the previous errors but now just fails even getting the correct DB_HOST.

Having DB_HOST set to 192.168.1.60 and the external database.php setup the same the docker still insists on looking at 172.17.0.1 for some reason.

I have tried removing DB_HOST env variable from my config and relying on the database.php but it gives the same error.

ERROR 1045 (28000): Access denied for user 'passbolt'@'172.17.0.1' (using password: YES)

database.php

        public $default = array(
                'datasource' => 'Database/Mysql',
                'persistent' => false,
                'host' => '192.168.1.60',
                'port' => '3308',
                'login' => 'passbolt',
                'password' => 'hjkkjhkjhkjhkj',
                'database' => 'passbolt',
                'prefix' => '',
                'encoding' => 'utf8',
        );

**Comment by dlen** [comment]
Could you provide the full command you are using plus the complete output of the container running?

**Comment by mannp** [comment]
Before wasting any more of your time @dlen I am going to try a generic unraid docker for nginx that I used for piwik and just modify it to add what is needed according to your manual config guide. So I can better understand what is going on.

I have removed all of the env variable settings for the db as I now point to the databsse.php with the correct details entered.

I also note that the MYSQL_ROOT_PASSWORD is not setup in the database.php, so does that get used elsewhere?

docker run -d --name="passbolt" --net="bridge" -e TZ="Europe/London" -e HOST_OS="unRAID/Linux" -e "MYSQL_ROOT_PASSWORD"="redacted" -e "URL"="passbolt.local" -p 447:443/tcp -v /mnt/user/data/docker/passbolt/Config/:/var/www/passbolt/app/Config/ passbolt/passbolt

**Comment by dlen** [comment]
hi  @mannp,
`MYSQL_ROOT_PASSWORD, HOST_OS, TZ` are not variables that passbolt docker uses.

For the database password the correct env variable is `DB_PASS`

**Comment by mannp** [comment]
hi @dlen yes those are not there for passbolt (except for MYSQL_ROOT_PASSWORD which I have mentioned by mistake from my mariadb docker for passbolt)

They don't affect passbolt docker looking at 'passbolt'@'172.17.0.1' instead of 'passbolt'@'192.168.1.60' as per the database.php config though.

**Comment by mannp** [comment]
Hi @dlen I have spent the time getting things configured on my mac via your official docker so I reduce the number of variables.

If I get everything configured on the mac I am hoping to transfer that config over to my docker server and use it from there.

Any errors would then be specific to the docker rather than my config or lack of understanding of the setup.

I cannot get email setup on the mac docker at the moment which means I cannot restore or transfer accounts, which is restrictive, so I am trying to get a fully working config on the mac first.

**Comment by mannp** [comment]
@dlen I now have most things as I want them and connected a /config mount to the docker where copied all the files from var/www/passbolt to config and and changed the owner to nginx:nginx.

I then edited the mount to be /var/www to the same external directory with the config and restarted the docker.

It seems to work, but ideally if a mount is added the files should be created the same as if they were inside the docker.

I have gotten there (I think) but need to keep an eye on permissions of the mount to make sure they don't cause me any problems.

Can you foresee any issues with this setup?

**Comment by dlen** [comment]
Your setup seems to be correct! 
I would like to point out that this container purpose is to be fully configurable using environment variables rather than mounting files. Considering this purpose, and trying to be flexible with users, specific instructions are provided for users to mount configuration files with special needs. (For instance configuration options that are not supported yet using environment variables.)
It is possible to mount a config directory from the host to centralize configuration files for backup purposes with the current container structure. Just create a 'config' directory on your host machine and mount whichever configuration files located inside this directory so you will be able to centralize the container configuration files for backups on your host right away.
This approach has the drawback of specifying mounts one by one but we are talking about 4 files `app.php core.php database.php and email.php` which seems a fair trade off.
With all that said, thanks for your feedback and your suggestions will be considered for future releases.

**Comment by mannp** [comment]
I couldn't actually get the individual files to mount as a file for some reason they kept mounting as a directory with the name app.php etc, so it was easier to mount a config directory with the files in it.

This happened on both mac and unraid linux.

The key for me is for a standard isolated config yours is fine, but in a scenario where people have multiple dockers running on the same server, this docker doesn't allow setting mariadb ports for example, so makes it impossible to even start the docker to get inside of the docker to actually edit database.php in the first place.

Perhaps mine was an isolated case in actually mounting the files directly, but that failure and mariadb port, turned the config into a far longer exercise that I had hoped.

**Comment by dlen** [comment]
Are you providing absolute path to the file when mounting it and providing the name of the file as described in the [advanced configuration](https://github.com/passbolt/passbolt_docker#advanced-configuration-1) section of the README?

**Comment by mannp** [comment]
Copied and pasted docker internal file path from advanced section and it gave me a directory not a file as it should.

**Comment by mannp** [comment]
I have resolved the file paths used to mount the config files directly, so am all up and running on 1.6.2 again.

If you find the time to add this feature, it is likely to need to check the permissions are correct on the external config directory and associated files, in order to allow updates and correct operation of the docker.

**Comment by dlen** [comment]
Could this be closed as part of #67 ?

**Comment by mannp** [comment]
Well neither are resolved and cannot be done, but if you say you are never going to add them.....

**Comment by dlen** [comment]
Hi again, it would be nice if you move this issue to the [community forum](https://community.passbolt.com/) as a feature request describing your use case.

**Comment by mannp** [comment]
The community isn't going to solve missing functionality in the passbolt docker, so I don't see the value in putting it to the community.
