### ISSUE TITLE
Address not available when sending email

### ISSUE THREAD

**Issue by berndartmueller** [passbolt/passbolt_docker#48]
Hello,

whenever trying to send an email, passbolt shows the error "Address not available". I already verified that my external smtp server is working.

By running 
`app/Console/cake EmailQueue.sender`
it shows
`Address not available
Email 59875196-8a7c-4cf7-a746-00b6ac130008 was not sent`

My environment config:
`
app_email_transport=Smtp
app_email_from_address=*****
app_email_from_name="*****"
app_email_host=smtp.world4you.com
app_email_port=25
app_email_timeout=30
app_email_username=*****
app_email_password=*****`

What could be the cause for this error? I also tried to look for this error in the source code but without success.

Thanks!

**Comment by dlen** [comment]
Hi @berndartmueller thanks for your interest in passbolt! 
Environment variables for passbolt container do not contain the 'app' prefix plus the are uppercased. Taking a quick look on your smtp provider documentation (https://www.world4you.com/en/hilfe-und-support/handbuecher/slide.26.html) seems like you have also set up an incorrect port for outgoing email (25 instead of 587) Your env should be set up like:
```EMAIL_TRANSPORT=Smtp
EMAIL_FROM=youremailsource
EMAIL_HOST=smtp.world4you.com
EMAIL_PORT=587
EMAIL_TIMEOUT=30
EMAIL_USERNAME=yourusername
EMAIL_PASSWORD=yourpass
```

**Comment by berndartmueller** [comment]
@dlen Thank you so much! I used the wrong environment variables as you pointed out.
