### ISSUE TITLE
Wrong url in emails

### ISSUE THREAD

**Issue by rgroothedde** [passbolt/passbolt_docker#50]
After upgrading the docker image to version 1.6.1.1, all links in the emails do redirect to localhost instead of the domain specified in the URL environment variable.

**Comment by tannerntannern** [comment]
I'm having the same issue.  I set the URL env variable to passbolt.localhost, but the links in the emails show up as http://localhost.

In addition, if I use a full URL (e.g. https://passbolt.localhost:443), I get the following error when trying to startup the docker container:

```
sed: -e expression #1, char 24: unknown option to `s'
```

**Comment by dlen** [comment]
Hi!

Thanks guys for your feedback. There is a bug indeed with the search and replace for the fullbaseurl param. It's kind of regression introduced when trying to drop the usage of default hostname "example.com" that was introducing problems for some users.

The bug is identified and it's fixed locally it will be pushed ASAP.

**Comment by tannerntannern** [comment]
Thanks for looking into this so quickly.  I love the product by the way.
