### ISSUE TITLE
Connection to database failed

### ISSUE THREAD

**Issue by dude1756** [passbolt/passbolt_docker#58]
Hi,
i have pulled the latest official passbolt image from docker hub and a mariadb image.
After several attempts I the container is not able to connect to the database as the access is denied for user.
However, I can connect to the database from another container ("Adminer") and from shell, using the standard user credentials. 
I user Docker on a Synology with configurations as follows:
**mariadb-container:** 
- IP 172.17.0.2
- database name: passbolt
- database password: P4ssb0lt
- user: passbolt (for testing on different servers: local, localhost, 172.17.0.4, 172.17.0.3) with all privileges

**passbolt-container:**
- IP 172.17.0.4
- environment parameters:
  
   -DB_USER: passbolt
   -DB_PASS: P4ssb0lt (->default)
    -DB_Name: passbolt
    - DB_HOST: 172.17.0.2 passbolt:local

As said, I can connect to the database via "Adminer"-Container with IP 172.17.0.3. I guess something is wrong with the DB_HOST parameter which I have changed already several times with  no success (xxx passbolt:172.17.0.4, passbolt:localhost, ...)

I would appreciate if you can help me out to get passbolt running.

Thx!

**Comment by dlen** [comment]
hi @dude1756 thanks for your interest in passbolt. Please note that env variable "DB_Name" should be "DB_NAME"

**Comment by dude1756** [comment]
Hi Dlen, 
Thx, you are right. I used the correct one already,  same Problem. Any other idea?

**Comment by mannp** [comment]
> DB_HOST: 172.17.0.2 **passbolt:local**

Is that a typo; why do you have passbolt:local after the DB_HOST variable, as mine is just an IP address.

Have you also tried setting DB_PORT to 3306 to be sure.

**Comment by dlen** [comment]
Hi @dude1756, as @mannp suggested maybe there is a typo in your setup. Is this issue still reproducing for you?

**Comment by dude1756** [comment]
Hi,
thx for your replies. Unfortunately, still not working with the following configurations:
-DB_USER: passbolt
-DB_PASS: P4ssb0lt (->default)
-DB_NAME: passbolt
-DB_HOST: 172.17.0.2
-DB_PORT: 3306
I can see in the container log, that now sth. is starting but aborting with the following error:
     "[31;4mError:[0m Database connection "Mysql" is missing, or could not be created"

**Comment by ben-st** [comment]
@dude1756 you can check the docker-compose file, i added.
While it awaits its pull request you can get it from here:
https://github.com/ben-st/passbolt_docker/blob/patch/docker-compose.yml
You can try if this works out for you, and if you can then check your env variables.

**Comment by dude1756** [comment]
Thanks for you help. Unfortunately it does not work and I had to go for another solution.

**Comment by r-chris** [comment]
Sorry to revive this old thread, but I am having similar issues and it's not a great experience. I would strongly encourage the passbolt team to make their docker container work out of the box to get people to use this. I do not mean to complain or be ungrateful for the hard work people put into this project - I simply hope this feedback is useful.

**Comment by dlen** [comment]
Hi @r-chris thanks for your feedback, we really appreciate it and we are sorry for the problems you are experiencing. It is however complicated to make passbolt container to run with no user interaction since it is a service that relies on other services such as a relational database or a smtp server to work. Considering this multiple service scenario, passbolt container has been designed to reduce user interaction to make things work.
In order to automate passbolt setup I encourage you to use a docker-compose file or check this one which has been useful to a good amount of passbolt users: [passbolt-compose](https://github.com/dlen/passbolt-compose).
I also recommend you to use our [community forum](https://community.passbolt.com) to post questions about your particular issue.
