### ISSUE TITLE
Alpine docker segfaults when generating keys

### ISSUE THREAD

**Issue by pierredadt** [passbolt/passbolt_docker#94]
**Envrionment:**
A `Kubernetes` cluster with `CoreOS` nodes.
Passbolt v`2.0.0-rc2-alpine`

**What was done:**
I tried to run the alpine docker without `rng-tools` installed on the Kubernetes nodes (wich is quite difficult, even impossible do to in my context).
I tried to generate entropy in the docker executing various commands

**What happened:**
After a while (longer than with `rng-tools`), the 4096b key is generated and writen to `/etc/ssl/certs/certificate.key` but the docker segfaults :
```
Generating a 4096 bit RSA private key
.................++
............................................++
writing new private key to '/etc/ssl/certs/certificate.key'
-----
Segmentation fault (core dumped)
```

**What was expected:**
I expected the process to take longer but still work. 

**Additional info / remarks :**
N/A

*Is there any way to alternatively generate entropy for gpg to create keys faster, and avoid a segmentation fault ?*

**Comment by dlen** [comment]
Hi @pierredadt !

Thanks for your report! This issue has already been reported and is one of the reasons (along with others) that we are migrating all docker images from alpine to debian. Mostly because problems with the fact that alpine uses musl libc instead of glibc. 
A new release of passbolt v2 is coming soon and and so a new release of the docker image which will be using debian as base image.
If you can't wait I encourage you to test v2.0.0-rc2 under the tag: passbolt/passbolt:develop-debian

**Comment by dlen** [comment]
@pierredadt a second read on your issue I realized you were struggling with the entropy generation.

In kubernetes or CoreOS environments (or any other container orchestrator) an option could be to mount server gpg key through a secret.

**Comment by pierredadt** [comment]
@dlen,
Thanks for your support, the debian version is indeed more functionnal !
I've created a set of kubernetes manifests to wrap passbolt deployment on a k8s context, from database and entropy tools to application, would you be interested in having them once I've validated them all ? (I still need to figure why the passbolt server listens on 127.0.0.1 instead of 0.0.0.0)
